server:
  port: ${SERVER_PORT:8761}
spring:
  application:
    name: discovery-service
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:discovery-service}
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:discovery-service}:${SERVER_PORT:8761}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://162.4.177.91:9411/api/v2/spans}
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: discovery-service
    stage: scaffold
