server:
  port: ${SERVER_PORT:8084}
spring:
  application:
    name: inventory-service
  data:
    redis:
      host: ${REDIS_HOST:162.4.177.91}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:local_redis_change_me}
      timeout: 3s
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:162.4.177.91:9092}
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      properties:
        enable.idempotence: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://162.4.177.91:5432/inventory_db}
    username: ${DB_USERNAME:inventory_user}
    password: ${DB_PASSWORD:local_inventory_change_me}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 10000
      initialization-fail-timeout: 30000
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://162.4.177.91:7080/realms/ecommerce/protocol/openid-connect/certs}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://162.4.177.91:8761/eureka/}
    registry-fetch-interval-seconds: 15
  instance:
    hostname: ${EUREKA_HOSTNAME:inventory-service}
    prefer-ip-address: false
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://162.4.177.91:9411/api/v2/spans}
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: inventory-service
    stage: scaffold
