global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: spring-apps
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - discovery-service:8761
          - api-gateway:8080
          - auth-service:8081
          - user-service:8082
          - catalog-service:8083
          - inventory-service:8084
          - order-service:8085
          - payment-service:8086
          - notification-service:8087
          - search-service:8088
  - job_name: infra-host
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: infra-containers
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: infra-search
    static_configs:
      - targets:
          - elasticsearch-exporter:9114
